---
spring:
  profiles: development
eureka:
  instance:
    hostname: development
  client:
    serviceUrl:
      defaultZone: http://development-peer/eureka/
---
spring:
  profiles: development-peer
eureka:
  instance:
    hostname: development-peer
  client:
    serviceUrl:
      defaultZone: http://development/eureka/
