---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: local
#  client:
#    serviceUrl:
#      defaultZone: http://peer2/eureka/
---
#spring:
#  profiles: peer2
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    serviceUrl:
#      defaultZone: http://peer1/eureka/
