---
spring:
  profiles: dev
travis:
  name: foo-dev
zuul:
  routes:
    kubo:
      path: /v1/kubo/**
      serviceIDd: kubo
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
---
spring:
  profiles: test
travis:
  name: foo-test
