---
spring:
  profiles: dev
travis:
  name: foo-dev
logging:
  level:
    com.sina.necomaker.gilgamesh.client.foo.feign.KuboClient: FULL
---
spring:
  profiles: test
travis:
  name: foo-test
